language: cpp

os: osx
osx_image: xcode8
compiler:
  - clang
  - gcc

jobs:
  include:
    - stage: build
      script: make # uses the default stage name "test"
    - stage: test
      script: make test
