language: cpp

os: osx
osx_image: xcode8
compiler:
  - clang

before_install:
  - ./install_deps.sh

stages:
  - build
  - test

jobs:
  include:
    - stage:  build
      script: make
    - stage:  test
      script: make test
